@contosopizza_HostAddress = http://localhost:5189

GET {{contosopizza_HostAddress}}/pizza/
Accept: application/json

# POST {{contosopizza_HostAddress}}/pizza/
# Content-Type: application/json

# {
#     "name":"Hawaii",
#     "isGlutenFree": false
# }

# PUT {{contosopizza_HostAddress}}/pizza/3
# Content-Type: application/json

# {
#     "id":3,
#     "name":"Hawaaiian",
#     "isGlutenFree":true
# }

# DELETE {{contosopizza_HostAddress}}/pizza/3

###